### ISSUE TITLE
Vue 2 support ?

### ISSUE THREAD

**Issue by IndexXuan** [fi3ework/vite-plugin-checker#1]
Great Works.
It seems use vue-tsc or tsc, does these work for vite + vue2 ?

**Comment by fi3ework** [comment]
@IndexXuan Not so familiar with Vue, could you tell me is there any `vue-tsc` liked library for vue2?

**Comment by IndexXuan** [comment]
maybe fork-ts-checker-webpack plugin
vti

**Comment by fi3ework** [comment]
Thanks for the pointing out. I'll take a look.

**Comment by fi3ework** [comment]
I'm trying to implement this based on Vetur language server.

**Comment by IndexXuan** [comment]
thanks a lot.

**Comment by IndexXuan** [comment]
It seems that vetur's vti not support vue slot type check and will be deprecated and replaced by volar(vue-tsc), maybe fork-ts-type-checker is better for Vue2.x ?
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin

**Comment by fi3ework** [comment]
Thanks @IndexXuan. I'm not going to implement the type checking like fork-ts-typecheck by myself (for now), because:
1. Vetur / Volar has done great battle-tested work for type checking. I can assume developers will use Vetur or Volar when they write code. So I think it's better to build the library upon Vetur and Volar's opened language server to make it easier to be used.
2. fork-ts-checker-webpack-plugin also have some scenes that can't cover, but Vetur can. https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/587.
3. It's mentioned on Volar's [documentaion](https://github.com/johnsoncodehk/volar) that Vue2 is also supported

> This tool required Vue 3 types from the @vue/runtime-dom module.
> 
> Vue 3 in itself includes the package @vue/runtime-dom. For Vue 2 you will have to install this package yourself:

So I think Vue2 is supported so far. All we need is waiting for the watch mode of vue-tsc releases.

4. I'll still try to support Vetur to check Vue2 to keep the developer habit and Volar is still in early stage.

What do you think. 😀

**Comment by IndexXuan** [comment]
I think you are right. and volar for Vue2.x I have a try, not very well(great for Vue3.x).
I think 2.x will exist long term, this feature will be very useful.

**Comment by Djaler** [comment]
Hello. vue-tsc works good for Vue 2

**Comment by IndexXuan** [comment]
@Djaler I dont think so. at least my Vue2.6 + composition-api project not good. do you have demo Vue2.x project so I can test and try. bro.

**Comment by Djaler** [comment]
I have no demo, but I use vue 2.6 with composition api on my work project and vue-tsc typechecking works for me. What doesn't work for you?

**Comment by IndexXuan** [comment]
I will check it later. I now use vetur in IDE and vti in CI. vue-tsc give some strange errors before. thanks for you reminder.

**Comment by fi3ework** [comment]
Vetur / VLS have been supported. Check the new README and have a try (renamed the package 😅).

**Comment by IndexXuan** [comment]
you are my hero. will try it.

**Comment by IndexXuan** [comment]
Back from vacation. will test it NOW and give feedback ASAP.

**Comment by IndexXuan** [comment]
It's perfect. Thank you very much.
I was warried about `v-slot="{ props }"` type check, it is(typed slot) not supported in Vue 2, this plugin ignore it too, and catch up all supported feature with Vue2 + vetur. Thanks a lot.

**Comment by IndexXuan** [comment]
errors overlay only show once, is it by design ? whilte the error message showup in browser console every time.
I can accept it and you can track it if necessary.

**Comment by fi3ework** [comment]
@IndexXuan  What does `errors overlay only show once` mean, the overlay should try to show up if there's an error after watched file changed 🤔

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/122350693-074a3780-cf80-11eb-82f3-84dc69e179f9.png)
HelloWorld.vue with props msg which type is `string | undefined` and src/views/home.vue import HelloWorld component and give `:msg="1"` which is number. the errors show `cannot assign number to string | undefined` only show once and after browser refresh, it is disappear and never showup.
![image](https://user-images.githubusercontent.com/6322673/122351217-85a6d980-cf80-11eb-839d-a90d17cf74c0.png)


It is because I didn't modify this file again, the watcher not fire. that is OK.

**Comment by IndexXuan** [comment]
我个人还好，据同事们体验，点击遮罩外侧或者刷新，错误就没了，还是有点突然或者会忘记处理，能 cache 住么 ...

**Comment by fi3ework** [comment]
@IndexXuan I also encountered this scenario while developing this plugin. 😅 I guess this might be a Vite related problem, the HMR sever (plugin checker server) didn't resend the error after refresh. I'm not sure whether we can detect a browser refresh action by Vite plugin system. I'll check it later.

**Comment by IndexXuan** [comment]
I wrong, too much v-slot errors in real-world project. I raise issue on vetur.

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vue-cli-plugin-vite/releases/tag/v1.2.2

**Comment by IndexXuan** [comment]
@Djaler How can you use vue-tsc/volar with Vue 2. for me, there are too much errors.
for example, v-model in Vue 2 means props.value + emit input and in Vue 3 means modelValue + update:modelValue, how volar handle this ?

just the repro demo [here](https://github.com/IndexXuan/vue2-volar-test-app/blob/master/src/views/Home.vue#L9). if you have v-model and props: { value: {type: String, required: true } }, you will got error when you use.
![image](https://user-images.githubusercontent.com/6322673/122679968-ae003380-d21f-11eb-8a2a-802943cfb2dc.png)
![image](https://user-images.githubusercontent.com/6322673/122679974-b3f61480-d21f-11eb-8fdf-a7d3b374241b.png)

**Comment by IndexXuan** [comment]
ref: https://github.com/johnsoncodehk/volar/issues/273

**Comment by Djaler** [comment]
I checked your example. Looks like volar have problems with `required: true` for `value` prop. I just have defaults in all such cases (for `v-model`). I think you should create an issue to Volar.

For the second question: yeah, by now vite-plugin-checker will not work with vue-tsc in dev mode

**Comment by IndexXuan** [comment]
@Djaler thanks a lot. I created issue to valor, the author said I should use vetur/vls/vti .

**Comment by Djaler** [comment]
I tried to use `vti` in my project and have a bunch of strange errors. Maybe I need to try again

**Comment by IndexXuan** [comment]
@Djaler me too. I am evan wrap VTI and ignore some strange errors.(sth like interface name not found?)
