### ISSUE TITLE
Please consider deploying improved 'watch' usage to 0.3.x stable

### ISSUE THREAD

**Issue by Yuddomack** [fi3ework/vite-plugin-checker#108]
Hi @fi3ework !

I am using root of vite config and 'eslint' option in vite-plugin-checker.
But I got an error when I edit a watched file.
(like this https://stackblitz.com/edit/vite-yasinn?file=rootA%2Fmain.js)

As a result, it was necessary to apply the root path to the cwd option of chokidar.
and The code has already been fixed and seems to have been released in 0.4.0 beta2.

https://github.com/fi3ework/vite-plugin-checker/blob/57c9e84bf6435713322db7511a2a2c68ce874a84/packages/vite-plugin-checker/src/checkers/eslint/main.ts#L96-L100

this `beta version` looks raising another error yet and is having difficulties because it is not synchronized with the documentation.
so Could you please release this commit as the 0.3 stable version?

ps. Thanks for making a awesome project 😆

**Comment by fi3ework** [comment]
@Yuddomack Would you like to describe what issue you encountered in 0.4? I prefer you to use 0.4.x as I fix many issues in 0.3. If you need any documentation, I can add it ASAP.

**Comment by fi3ework** [comment]
If you need a example of configuration for ESLint in 0.4.x. Here's an example https://github.com/fi3ework/vite-plugin-checker/blob/v0.4.x/playground/eslint/vite.config.ts

**Comment by fi3ework** [comment]
@Yuddomack I think I figured out the reason. It's because ESLint 8 used an exports map and some path is not defined in it. I'll take a look at it.

**Comment by fi3ework** [comment]
I also find one function https://github.com/fi3ework/vite-plugin-checker/blob/v0.4.x/packages/vite-plugin-checker/src/main.ts#L155 which 0.4.x used requires `vite >=2.6.8`. I made a new playground with eslint^7 & vite^2.6.8 it goes well. https://stackblitz.com/edit/vite-jh9mtj?file=vite.config.js

**Comment by fi3ework** [comment]
published a new beta version and bump to beta.6 it works now. https://stackblitz.com/edit/vite-kq51d6?file=package.json

**Comment by fi3ework** [comment]
0.4.0 released
