### ISSUE TITLE
References to checker plugin in production build

### ISSUE THREAD

**Issue by Grisu118** [fi3ework/vite-plugin-checker#112]
The new version 0.4.0 adds the following line to the index.html
```html
<script type="module">import { inject } from "/@vite-plugin-checker-runtime"; inject();</script>
```

This is done also for a production build, in my eyes this is wrong and should only happen for dev builds.

**Comment by fi3ework** [comment]
@Grisu118 Sorry for my stupid mistake 😅. I made a hotfix and published 0.4.1. I'll add a test case for this issue later. Thanks for your good catch! Please upgrade to 0.4.1 🤗. https://github.com/fi3ework/vite-plugin-checker/blob/main/packages/vite-plugin-checker/CHANGELOG.md#041-2022-02-11
