### ISSUE TITLE
How to slient the ignored file warning

### ISSUE THREAD

**Issue by greenhat616** [fi3ework/vite-plugin-checker#115]
Because of my program using auto-generated .d.ts, which  is incompatible with my custom eslint rules, I had to ignore these files.

This issue is caused by `eslint 'ignore_file'` like:
```
❯ pnpm eslint "./src/auto-imports.d.ts"

/root/Programs/*****/auto-imports.d.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```

-------------
attachment 1:
emmm, is `eslint.dev.eslint`  defined in `vite.config.js`? THX

**Comment by fi3ework** [comment]
I didn't quite understand the issue. I guess that you want ignore some paths in the development mode. You can pass argv to ESLint as it documented. e.g. `npx eslint --ignore-path tmp/.eslintignore file.js`. Is this what you need? https://eslint.org/docs/user-guide/command-line-interface#ignoring-files

**Comment by Yuddomack** [comment]
@greenhat616 

I also had a similar situation, eslint tells you which path was ignored. (in my case, notified `coverage/...` from jest reports ignored)
solved it by excluded from inspection, not ignore pattern.

so you can try

```
eslint "**/!(*.d).*"
```

I'm not sure it is best, but this will be a temporary solution (If the notification bothers you)

**Comment by greenhat616** [comment]
> I didn't quite understand the issue. I guess that you want ignore some paths in the development mode. You can pass argv to ESLint as it documented. e.g. `npx eslint --ignore-path tmp/.eslintignore file.js`. Is this what you need? https://eslint.org/docs/user-guide/command-line-interface#ignoring-files

I'm sorry that I reply you so lately. I have tried with `--ignore-path` flag before. when it first launched, no error would appear. 
BUT when HMR occurs, it might show `warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`.

I used `unplugin-auto-import` and `unplugin-vue-components` to finish auto import deps, functions and generate necessary type definition files. 

**I assume that watch trigger might exec like `pnpm eslint "./src/auto-imports(which-is-ignored).d.ts"` is the cause because auto-generated files could changed.**

**Comment by greenhat616** [comment]
> @greenhat616
> 
> I also had a similar situation, eslint tells you which path was ignored. (in my case, notified `coverage/...` from jest reports ignored) solved it by excluded from inspection, not ignore pattern.
> 
> so you can try
> 
> ```
> eslint "**/!(*.d).*"
> ```
> 
> I'm not sure it is best, but this will be a temporary solution (If the notification bothers you)

@Yuddomack Thank you for your workaround. I will have a try later. THX
