### ISSUE TITLE
Readme is rather opaque in this section

### ISSUE THREAD

**Issue by geewhizbang** [fi3ework/vite-plugin-checker#121]
This instruction on readme is completely incomprehensible. Which file is being modified, for example:

Make sure [eslint](https://www.npmjs.com/package/eslint) is installed as a peer dependency.  \\What does this mean?

Add eslint field to plugin config, the lintCommand is required, it's quite like the lint command of your project. The default [root](https://vitejs.dev/config/#root) of the command uses Vite's root. 

export default {
  plugins: [
    checker({
      eslint: {
        lintCommand: 'eslint "./src/**/*.{ts,tsx}"',
      },
    }),
  ],
}

**Comment by fi3ework** [comment]
> Make sure [eslint](https://www.npmjs.com/package/eslint) is installed as a peer dependency. \What does this mean?

It means, if you wanna use ESLint checker. You should install eslint to your project as it will be invoked and add eslint filed to the checker config.

> it's quite like the lint command of your project.

Yes, it is. It's only an example. You can write your lint command there. It's quite like the lint command in your lint command in packagejson.script.

**Comment by geewhizbang** [comment]
This is a non-explanatory explanation.
