### ISSUE TITLE
add vue-tsc watch mode support

### ISSUE THREAD

**Issue by olemarius** [fi3ework/vite-plugin-checker#124]
### Is your feature request related to a problem? Please describe.

running vue-tsc --watch is too slow, need to run it via this plugin 

### Describe the solution you'd like

Add new support for vue-tsc in this plugin

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Thanks! I'm looking into the new released vue-tsc and working on it.

**Comment by fi3ework** [comment]
https://github.com/johnsoncodehk/volar/issues/1082

**Comment by fi3ework** [comment]
released in 0.4.4
