### ISSUE TITLE
Unwanted typescript errors when dev server is started

### ISSUE THREAD

**Issue by smtrd3** [fi3ework/vite-plugin-checker#130]
### Describe the bug

Note that I am running vite under a monorepo setup, specifically using pnpm workspaces. I just bootstrapped the app with react-ts and vite-plugin-checker is the only plugin installed. I can see the following error 

```
5:27:36 AM [vite] vite.config.ts changed, restarting server...
5:27:36 AM [vite] server restarted.

 ERROR(TypeScript)  Duplicate identifier 'Prepend'.
 FILE  /home/<USER>/project/node_modules/.pnpm/@types+eslint@7.29.0/node_modules/@types/eslint/helpers.d.ts:1:6

  > 1 | type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
      |      ^^^^^^^
    2 |     ? Result
    3 |     : never;
    4 |

 ERROR(TypeScript)  Duplicate identifier 'Prepend'.
 FILE  /home/<USER>/project/node_modules/.pnpm/@types+eslint@8.4.1/node_modules/@types/eslint/helpers.d.ts:1:6

  > 1 | type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
      |      ^^^^^^^
    2 |     ? Result
    3 |     : never;
    4 |

[TypeScript] Found 2 errors. Watching for file changes.
```

Screenshot:
<img width="1094" alt="Screenshot 2022-03-31 at 11 15 59 AM" src="https://user-images.githubusercontent.com/37965074/160985230-d94ad1fc-1592-4549-a64b-30f3e5be66ab.png">

This is my config file:
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import checker from 'vite-plugin-checker'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), checker({
    typescript: {
      root: '.', tsconfigPath: 'tsconfig.json'
    }
  })],
  server: {
    host: '0.0.0.0',
    port: 3000,
  }
})
```

### Reproduction

- add new module under a pnpm monorepo (with eslint being a dependency in other workspace packages)
- start the dev server with the ``vite-plugin-checker`` plugin added

### Expected behavior

The plugin should only typecheck source folder contents

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 DO-Regular
    Memory: 482.94 MB / 3.84 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  npmPackages:
    vite-plugin-checker: ^0.4.4 => 0.4.4
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
any issues reported by running `tsc --noEmit`?

**Comment by val1984** [comment]
I got a similar issue with `vite@2.9.1` and `vite-plugin-checker@0.4.5`. Turns out it was because `skipLibCheck` was set to `true` in my project `tsconfig.json` file.

**Comment by fi3ework** [comment]
@val1984 I think setting `skipLibCheck` to true can eliminate this report. And could you run `tsc --noEmit` in your project to verify is it a right report from tsc?

**Comment by val1984** [comment]
Sorry, I wasn't clear in my previous message but it definitely fixed the issue for me.

@smtrd3 Can you try this solution?

**Comment by fi3ework** [comment]
For anyone who encounters similar issues. You can run `tsc --noEmit` or `vue-tsc --noEmit` under your project. If the command reports the same issues, then there's nothing to do with vite-plugin-checker cause it just forwards the issues. If not, please leave a comment below.

**Comment by guiphc** [comment]
I am having the same problem, in my case I am getting way more erros from node_modules libs:

![image](https://user-images.githubusercontent.com/7368169/167036119-6267e099-b090-4aa5-91c5-6e6a7693fdb8.png)
![image](https://user-images.githubusercontent.com/7368169/167036170-96ee0479-378b-48d1-91b4-9d0bbfaae4f8.png)

**Comment by fi3ework** [comment]
@guiphc add `skipLibCheck: true` to tsconfig

**Comment by guiphc** [comment]
> @guiphc add `skipLibCheck: true` to tsconfig

this did not work, for some reason looks like the plugin did not respect my tsconfig.

**Comment by fi3ework** [comment]
@guiphc Provide a stackblitz link please

**Comment by TurtIeSocks** [comment]
I'm _kind of_ experiencing this as well, though it's more of a bonus than a bug for me. If I run `tsc --noEmit` the errors that are being reported by the plugin are indeed picked up by TypeScript, but these errors aren't reported in the IDE (VS Code). I know Vite doesn't really care, but they're of course not reported during the `vite build` process as well, meaning I probably never would have caught these if I wasn't using the plugin (❤️). 

Is this a TypeScript bug, a VS Code bug or? Any hints on how I can make sure that these bugs are reported in the IDE as well?

**Comment by lake2** [comment]
same issue +1.
If I run `tsc --noEmit`, there are no errors.
But when I use this plugin, it report errors from `node_modules` folder.
It maybe caused by `monorepo`
