### ISSUE TITLE
eslint rule name is not displayed

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [fi3ework/vite-plugin-checker#132]
### Describe the bug

Eslint shows the rule name when there's an error or warning, but it is not visible in the plugin (neither in console nor in the overlay)

Console:
![image](https://user-images.githubusercontent.com/15625235/161827079-7dc50849-74fd-4981-add9-b4cfeaef4f57.png)

Overlay:
![image](https://user-images.githubusercontent.com/15625235/161827134-21a20382-050f-4cb3-9315-f5ac339aa692.png)

### Reproduction

Just create a code breaking some eslint rule

### Expected behavior

Rule name is visible in console and in overlay

Screenshot from IDE:
![image](https://user-images.githubusercontent.com/15625235/161827204-4a637c41-e436-4b3c-9cb7-3fbfd2f872b6.png)

### System Info

```shell
win10, node 16, vite 2.9, vite-plugin-checker 0.4.5, vue 2
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Good catch!
