### ISSUE TITLE
Now showing errors

### ISSUE THREAD

**Issue by Gercov** [fi3ework/vite-plugin-checker#134]
### Describe the bug

Always showing this message: `[vue-tsc] Found 0 errors. Watching for file changes.` even errors

### Reproduction

Docs steps by install vite-plugin-checker

### Expected behavior

Throw error

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 6.92 GB / 15.93 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.29)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite-plugin-checker: latest => 0.4.5
```

### Additional context

![image](https://user-images.githubusercontent.com/51914212/162196333-65efac41-ea64-43fd-983a-dfb921e04ab1.png)
![image](https://user-images.githubusercontent.com/51914212/162196509-6b5b4830-b913-4b23-975c-13d4106c1e1a.png)
![image](https://user-images.githubusercontent.com/51914212/162196520-6aef6517-7eba-4c18-aa60-1cd724dca056.png)

```
    "typescript": "^4.6.2",
    "vite": "^2.8.4",
    "vite-plugin-checker": "latest",
    "vitest": "^0.5.0",
    "vue-tsc": "^0.33.9"
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Gercov** [comment]
> 

![image](https://user-images.githubusercontent.com/51914212/162256456-ada8851e-dcf3-4790-88f6-e71d7f301a24.png)
Nothing

**Comment by Gercov** [comment]
@fi3ework 
Nothing 
![image](https://user-images.githubusercontent.com/51914212/162256520-fa0e13d9-9550-4432-8897-cc44d09577d4.png)

**Comment by Gercov** [comment]
@fi3ework 
![image](https://user-images.githubusercontent.com/51914212/162257034-6bd8d1a6-54ac-460a-97ae-1c0f811cc686.png)

**Comment by fi3ework** [comment]
So that should be `vue-tsc` related issue. vite-pluigin-checker only reports what issues the checker found. I saw you are using `vueJsx`, guess that's not supported by vue-tsc 🤔. You can open an issue in https://github.com/johnsoncodehk/volar. I'm going to close issue since it's upstream related.

**Comment by Gercov** [comment]
@fi3ework Ok thanks
