### ISSUE TITLE
Svelte support?

### ISSUE THREAD

**Issue by predragnikolic** [fi3ework/vite-plugin-checker#143]
### Is your feature request related to a problem? Please describe.

Currently this plugin supports vanilla JS / TS, React, Vue2, Vue3, and I do not see an option to enable this for svelte projects generated with vite.

It would be good if it also supported svelte.

### Describe the solution you'd like

Add a svelte option, that probably uses [svelte-check](https://www.npmjs.com/package/svelte-check).

### Describe alternatives you've considered

I have seen this PR https://github.com/fi3ework/vite-plugin-checker/pull/73,
but it seems stale.

### Additional context

/

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by jankaderabek** [comment]
Could be nice to finish opened PR #73 Is there something that needs to be done to merge that PR or somehow help with that?

**Comment by fi3ework** [comment]
@jankaderabek Yes, #73 is bit obsolete and needs to tweak for the `main` branch. I haven't start to continue the work of #73 . Any PR will be welcomed.

**Comment by predragnikolic** [comment]
I lost interest
