### ISSUE TITLE
Vite 3 support

### ISSUE THREAD

**Issue by Artur-** [fi3ework/vite-plugin-checker#147]
### Is your feature request related to a problem? Please describe.

This plugin seems to work with Vite 3 but installing it is a bit of a hassle as it has
```
  "peerDependencies": {
    "vite": "^2.0.0"
  },
```

As a result `npm install` complains that
```
npm ERR! Found: vite@3.0.0-beta.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"v3.0.0-beta.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0" from vite-plugin-checker@0.4.5
npm ERR! node_modules/vite-plugin-checker
npm ERR!   dev vite-plugin-checker@"0.4.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Describe the solution you'd like

Expand the peer dependency to cover Vite 3 and pre-releases of Vite 3

### Describe alternatives you've considered

Other possibilities would be
1. Remove the peer dependency
2. Create a new version of the plugin only for Vite 3

Not sure which one is preferable here

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
I'll test does the plugin works fine with Vite3 out of the box tomorrow. If it works fine, I'll add ^3 support and release a patch version quickly.
