### ISSUE TITLE
Switch from jest to vitest?

### ISSUE THREAD

**Issue by gkiely** [fi3ework/vite-plugin-checker#152]
### Is your feature request related to a problem? Please describe.

Move to using [vitest](https://vitest.dev/) for testing.
 
This will remove jest dependencies, speed up tests and align with vite.

### Describe the solution you'd like

Project is using vitest

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Already using Vitest! 🚀
