### ISSUE TITLE
Memory leak occurs when using vue2.7+vuetsc

### ISSUE THREAD

**Issue by wwh0219** [fi3ework/vite-plugin-checker#156]
### Describe the bug

Using vue2.7+vuetsc, memory leak will occur after saving many times

### Reproduction

This is the repo
[https://github.com/wwh0219/vite-plugin-checker-demo](https://github.com/wwh0219/vite-plugin-checker-demo)
It's a reproduction video
[https://youtu.be/rsOXuz869QU](https://youtu.be/rsOXuz869QU)

### Expected behavior

there is no memory leak

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
    Memory: 8.10 GB / 15.93 GB
  Binaries:
    Node: 16.14.2 - E:\node-global\nodejs\node.EXE
    Yarn: 1.22.18 - E:\node-global\npm\yarn.CMD
    npm: 8.7.0 - E:\node-global\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite-plugin-checker: ^0.4.9 => 0.4.9
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
let's track this in #127
