### ISSUE TITLE
vite build hangs forever

### ISSUE THREAD

**Issue by bbugh** [fi3ework/vite-plugin-checker#16]
After adding Checker, my `vite build` began to hang forever. I tried multiple different options `typescript: true`, `vueTsc: true` (with the package installed), etc. 

The build runs fine, but when it is complete, it sits forever. CI deploy waited for ~15 minutes before timing out.

Here is an example repo with a tag at the commit where it broke:

https://github.com/bbugh/vue-tsx-tailwind-starter/releases/tag/checker

**Comment by bbugh** [comment]
I'm not sure what the relation to https://github.com/yuxino/vite-plugin-ts-checker is, but using that plugin works.

**Comment by fi3ework** [comment]
Hi @bbugh! The forever hang problem is known and I'm trying to fix it. And it has almost done.

https://www.npmjs.com/package/vite-plugin-ts-checker is the predecessor of `vite-plugin-checker`. I renamed the package as it may work with different checkers. You can use `vite-plugin-ts-checker` for now. I'll fix the bug and release a version ASAP and let you know. We can leave this issue open.

**Comment by IndexXuan** [comment]
Yes, only use it in development mode right now.

**Comment by fi3ework** [comment]
fixed in 0.2.0

**Comment by bbugh** [comment]
Seems to be working now, thanks!
