### ISSUE TITLE
Request for switch to toggle overlay

### ISSUE THREAD

**Issue by nicholastiong** [fi3ework/vite-plugin-checker#164]
### Is your feature request related to a problem? Please describe.

Current type checking overlay in development mode is blocking some part of the UI (e.g. side nav).
<img width="120" alt="Screenshot 2022-08-17 at 10 33 22 PM" src="https://user-images.githubusercontent.com/63196700/185162476-219c0b9c-be54-4637-8219-19943473aea6.png">

### Describe the solution you'd like

It would be good if there is a switch to toggle the overlay.

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
You can add a custom style to the badge, see documentation https://vite-plugin-checker.netlify.app/configuration/config.html. Does it satisfy?

**Comment by fi3ework** [comment]
close as inactive, feel free to reopen if there's any following questions.
