### ISSUE TITLE
.vue files only checked by ESlint when they are modified

### ISSUE THREAD

**Issue by AndreKR** [fi3ework/vite-plugin-checker#169]
### Describe the bug

This is my `vite.config.ts`:
```ts
export default defineConfig({
  plugins: [
    vue(),
    checker({ eslint: { lintCommand: 'eslint src' } })
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    open: true,
  },
  base: './'
})
```

This is my `.eslintrc.json`:
```json
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:vue/vue3-recommended"
    ],
    "parserOptions": {
        "ecmaVersion": "latest",
        "parser": "@typescript-eslint/parser",
        "sourceType": "module"
    },
    "plugins": [
        "vue",
        "@typescript-eslint"
    ],
    "rules": {
        "indent": ["error", "tab"],
        "comma-dangle": "off",
        "no-tabs": ["error", { "allowIndentationTabs": true }],
        "vue/html-indent" : ["error", "tab"],
        "vue/multi-word-component-names": "off",
        "vue/no-multiple-template-root": "error",
        "@typescript-eslint/no-unused-vars": "warn",
        "no-unused-vars": "warn",
        "quotes": ["warn", "single", { "avoidEscape": true }],
        "semi": "error"
    }
}
```

Entrypoint and Vue app component:
```ts
import {createApp} from 'vue';
import App from './App.vue';

const app = createApp(App);

app.mount('#app');
```
```vue
<script setup>
import Foo from './Foo.vue';
</script>

<template>
	<div>
		<Foo />
	</div>
</template>
```

Component `Foo` contains a lint error:
```vue
<template>
	<div>
    {{ foo }}
	</div>
</template>

<script setup>

const foo = 'i have no semicolon'

</script>
```

When I now run `vite`, it will show

> [ESLint] Found 0 error and 0 warning

Only if I modify `Foo.vue` **while Vite is already running** it will detect the lint error in the file.

### Reproduction

You can create a project with the above files yourself or you can check out the [repro repo](https://github.com/AndreKR/vite-plugin-checker-issue-169) I have provided, and then:

Make sure you have `yarn` installed. If not, Node > 16.10 should auto-install it if instructed so with `corepack enable`.

Then run:
```
yarn
yarn run dev
```

You should see

> [ESLint] Found 0 error and 0 warning

If you *then* edit something in `Foo.vue` (add some text to the string or something, but leave the semicolon missing) and save the file, then it will show the lint error.

### Expected behavior

The lint error should be detected already when Vite is starting or at least when the page is loaded.

Or - if I have misconfigured my ESlint somehow - then I would expect it to not detect the line error *at all*.

Detecting it only when the file is modified is just wrong.

### System Info

```shell
System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
    Memory: 1.15 GB / 15.70 GB
  Binaries:
    Node: 16.14.2 - C:\dev-tools\nodejs\node.EXE
    Yarn: 1.22.19 - C:\dev-tools\nodejs\yarn.CMD
    npm: 8.5.0 - C:\dev-tools\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Internet Explorer: 11.0.9600.17840
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
I successfully re-produced the issue. The lint command should be write like

```
lintCommand: 'eslint src/**/*.vue'`
```

instead of

```
lintCommand: 'eslint src'
```

I ran `yarn eslint src` and nothing happened, but `yarn eslint src/**/*.vue` show the error. So the plugin should not show the error cause the lint command also did not work with ESLint itself, which means it should report an issue after editing, either.
https://github.com/fi3ework/vite-plugin-checker/pull/172 should have fix this issue. And the solution for this issue is to change the lint command.
