### ISSUE TITLE
Overlay doesn't work with single spa

### ISSUE THREAD

**Issue by DoctorRyner** [fi3ework/vite-plugin-checker#171]
### Describe the bug

Overlay is shown at the page of microfrontend but on not in the root microfrontend application

### Reproduction

If we have single-spa app, and our app with this checker mounts when our single-spa app goes to a route :3000/someAppWithOverlay then there is no overlay. Overlay appears when you go to :yourLocalAppPort

### Expected behavior

A way to mount overlay when it's opened at :3000/someAppWithOverlay

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 130.22 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /opt/homebrew/bin/node
    Yarn: 3.2.3 - ~/Library/pnpm/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 100.0.2
    Safari: 15.5
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by DoctorRyner** [comment]
I tried to implement this but I don't know where to start, my experiments failed :(

**Comment by fi3ework** [comment]
Which micro-frontend framework you're using, such as Qiankun? Could you provide a mini re-production?

**Comment by DoctorRyner** [comment]
Just single-spa. Ok, I'll do a reproduction in spare time
