### ISSUE TITLE
Doesn't seem to work with `--fix`

### ISSUE THREAD

**Issue by johnnyshankman** [fi3ework/vite-plugin-checker#180]
### Describe the bug

When passing in `--fix` my linter always passes and never fixes anything. It won't report any issues *and* won't fix them it seems? It could be fooling itself into thinking it fixed them but then didn't actually write the changes back.

### Reproduction

```
plugins: [
    vue(),
    checker({
      vueTsc: true,
      eslint: {
        lintCommand: 'eslint "./src/**/*.{ts,vue}" --fix',
      },
    }),
  ],
  ```

### Expected behavior

Should write the changes back to the files.

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.48 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 96.1.32.113
    Chrome: 106.0.5249.119
    Firefox: 104.0.2
    Safari: 15.1
  npmPackages:
    vite-plugin-checker: ^0.5.1 => 0.5.1
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by curiousyigit** [comment]
I confirm this bug

**Comment by fi3ework** [comment]
This plugin is designed for check only, so auto-fixing is not in the target scope. Please remove `--fix` from the plugin config. I'll update doc to point this out.

**Comment by fi3ework** [comment]
update in https://github.com/fi3ework/vite-plugin-checker/commit/990a08892c957da218003e7bfe338fcd83ccf4b7.
