### ISSUE TITLE
Vitest support

### ISSUE THREAD

**Issue by Faithfinder** [fi3ework/vite-plugin-checker#196]
### Is your feature request related to a problem? Please describe.

I'd love to be able to enforce running tests as part of the build

### Describe the solution you'd like

Add `vitest` param to this plugin. One of the options should probably be specifying a subset of tests - I'd prefer to only run unit tests like this, not e2e tests.

### Describe alternatives you've considered

`build` command in package.json is `"build": "vitest run && vite build",`

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Vitest is about unit tests and it already has a fantastic UI https://vitest.dev/guide/ui.html. I do not think this plugin should be an all-in-one suite. The plugin should focus on its scope.
