### ISSUE TITLE
[Help wanted] Overlay not displaying in a Nuxt 3 application

### ISSUE THREAD

**Issue by Litarvan** [fi3ework/vite-plugin-checker#197]
### Describe the bug

When using `vite-plugin-checker` in a Nuxt project, the overlay is not injected in the dev server HTML.

### Reproduction

```
npx nuxi init hello-world && cd hello-world
npm i
npm i -D vite-plugin-checker eslint eslint-plugin-vue @typescript-eslint/parser @typescript-eslint/eslint-plugin
```

Until [a Jiti issue](https://github.com/unjs/jiti/issues/105) is fixed, replace line 13 of `node_modules/vite-plugin-checker/dist/esm/logger.js` with this one:
```javascript
const { URI } = _require('vscode-uri');
```

Edit `nuxt.config.ts` to register the plugin:
```typescript
import checker from 'vite-plugin-checker';

export default defineNuxtConfig({
  vite: {
    plugins: [
      checker({
        eslint: { lintCommand: 'eslint ./**/*.{ts,vue}' }
      })
    ]
  }
})
```

Add a basic `.eslintrc.js`:
```javascript
module.exports = {
  root: true,
  env: {
    browser: true,
    es2021: true,
    node: true
  },
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
    project: './tsconfig.json',
    extraFileExtensions: ['.vue']
  },
  plugins: [
    'vue', //
    '@typescript-eslint'
  ],
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:@typescript-eslint/strict',
  ]
};
```

Add an example linting issue in the `app.vue` file:
```html
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>

<script lang="ts" setup>
function unused() {}
</script>
```

Run the app:
```
npm run dev
```

Open http://localhost:3000/

### Expected behavior

The overlay should display in `http://localhost:3000/` but it isn't, since the HTML `<script>` code with the plugin runtime isn't injected in the dev server HTML.
The linting error for the unused function is displayed like expected in the dev server console.

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 843.11 MB / 32.00 GB
    Shell: 3.5.1 - ~/.nix-profile/bin/fish
  Binaries:
    Node: 18.8.0 - ~/.nix-profile/bin/node
    npm: 9.2.0 - ~/Library/pnpm/npm
  Browsers:
    Firefox Developer Edition: 108.0
    Safari: 16.1
  npmPackages:
    vite-plugin-checker: ^0.5.3 => 0.5.3 
    nuxt: ^3.0.0 => 3.0.0
```

### Additional context

This is probably related to #168 , a similar workaround as described in the comments works but not if you edit the HMR port (which isn't a problem without Nuxt) :/

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Took a look at a nuxt demo, I'm afraid there need to be an nuxt module to extend nuxt https://nuxt.com/docs/guide/going-further/modules becauae `transformIndexHtml` is not called by nuxt.

**Comment by fi3ework** [comment]
It took a few hours to investigate how to show the error overlay in Nuxt3.  I haven't figured out how to implement it. I got the following clues though.

## Why is the overlay not displayed?

1. vite-plugin-checker(vpc) uses `resolveId` and `load` plugin methods of Vite to serve a virtual module in runtime, for example, `https://localhost:3000/@vite-plugin-checker-runtime`. It works fine in a SPA and a classic backend-integration application. But Nuxt takes over all the routes. So the request sent from the browser is received by Nuxt3 instead of the Vite dev server.
2. I tried using a hack method to make a minimal working workaround as below:
```js
// nuxt.config.ts
  devServerHandlers: [
    {
      route: '/@vite-plugin-checker-runtime-entry',
      handler: (event) => {
        const RUNTIME_CLIENT_RUNTIME_PATH = '/@vite-plugin-checker-runtime'
        const config = {}
        const base = '/'
        event.node.res.setHeader('Content-Type', 'application/javascript')
        event.node.res.end(`
        import { inject } from "${base}${RUNTIME_CLIENT_RUNTIME_PATH.slice(1)}";
inject({
  overlayConfig: ${JSON.stringify(config)},
  base: "${base}",
});`)
      },
    },
    {
      route: '/@vite-plugin-checker-runtime',
      handler: (event) => {
        event.node.res.setHeader('Content-Type', 'application/javascript')
        event.node.res.end(runtimeCode)
      },
    },
  ],
```
Luckily, the client can fetch the runtime code. But, the WebSocket is lost 😅. vpc uses `import.meta.hot.on`, provided by Vite's native client-server communication solution. But it seems like Nuxt deligated the WebSocket and no custom event is sent to the client so the `import.meta.hot.on('vite-plugin-checker:error', callback)` can not receive any message.

Does anyone get any clues to figure out how to bypass these blocks? Thanks! 🫡

**Comment by Litarvan** [comment]
I used dirty workarounds to make it work, since the plugin has way too much value.

First, to fix the Jiti bug, use the following patch file :
```patch
-TODO: Enable after cleanup-- node_modules/vite-plugin-checker/dist/esm/logger.original.js	2022-12-28 16:26:49
+++ node_modules/vite-plugin-checker/dist/esm/logger.js	2022-12-28 16:27:06
@@ -10,7 +10,7 @@
 import { ACTION_TYPES, DiagnosticLevel } from "./types.js";
 import { isMainThread } from "./utils.js";
 const _require = createRequire(import.meta.url);
-const { URI } = vscodeUri;
+const { URI } = _require('vscode-uri');
 const defaultLogLevel = [
   DiagnosticLevel.Warning,
   DiagnosticLevel.Error,
@@ -326,4 +326,4 @@
   uriToAbsPath,
   wrapCheckerSummary
 };
-//# sourceMappingURL=logger.js.map
\ No newline at end of file
+//# sourceMappingURL=logger.js.map
```

You can tell npm/yarn/pnpm to automatically apply it by adding it to the postinstall hook (which requires `patch` to be installed):
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare && patch -N node_modules/vite-plugin-checker/dist/esm/logger.js PATH_TO_THE/checker-logger.patch"
  },
  "dependencies": {
    "nuxt": "^3.0.0",
    "vite-plugin-checker": "^0.5.4"
  }
}
```

Then, to manually register the overlay, I've made a Vue component (which I called `DevelopmentCheckerRuntime.vue`):
```html
<template>
  <div />
</template>

<script lang="ts" setup>
onMounted(async () => {
  // @ts-expect-error - Don't worry, the module exists
  // eslint-disable-next-line
  const { inject } = await import('/@vite-plugin-checker-runtime');

  inject({
    overlayConfig: {},
    base: '/'
  });
});
</script>
```

Which I register in the `app.vue` at the root of the project, but only for development:
```html
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>

    <DevOnly>
      <DevelopmentCheckerRuntime />
    </DevOnly>
  </div>
</template>
```

By using all of this, the plugin should work perfectly.

**Comment by fi3ework** [comment]
@Litarvan I see. You installed vite-plugin-checker manually. The issue I spend hours trying to hack is in another usage, which is integrated by Nuxt(https://nuxt.com/docs/guide/concepts/typescript#stricter-checks) already. I think both are fine and maybe a native Vite plugin usage is better, I'll check this later, thanks!

**Comment by fi3ework** [comment]
@Litarvan I had successfully run the workaround with the hack you mentioned. But I noticed that the plugin's life cycle is called twice when integrating with Nuxt (includes `config` `configureServer`), which leads to console.log in the terminal twice. Do you have the same issue, too? I guess it's cuased by Nuxt. 🤔

**Comment by Litarvan** [comment]
Yup! I have the same issue, didn't think about it that much since it had no real impact (at least I thought?) but I do have several console logs at the same time

**Comment by fi3ework** [comment]
I found it's because Nuxt is building twice. It has another build process using `ssrBuild` https://vitejs.dev/config/#conditional-config. Luckily, the flag is exposed to the hook and easy to be skipped.

**Comment by fi3ework** [comment]
After 0.5.5, there's a way to use with Nuxt, have a try! https://vite-plugin-checker.netlify.app/faq/integration.html#overlay-does-not-display-in-development-mode-1
