### ISSUE TITLE
Refactor client <-> server communication by Vite's native API

### ISSUE THREAD

**Issue by fi3ework** [fi3ework/vite-plugin-checker#200]
Didn't notice https://vitejs.dev/guide/api-plugin.html#client-server-communication ever, this could remove much hand-made websocket logic 😅.

**Comment by Artur-** [comment]
Would be great because right now the connection logic does not seem to match between this plugin and Vite. This plugin connects directly to the Vite server port even when Vite uses the current browser URL.

**Comment by Artur-** [comment]
..which seems to be what #189 is about

**Comment by Artur-** [comment]
Ah, seems this was fixed in 0.5.3 and I am still on 0.5.2. Never mind me then..

**Comment by fi3ework** [comment]
@Artur-  I haven't checked #189 yet. Did you mean #189 has been fixed in 0.5.3?

**Comment by Artur-** [comment]
Seems like the current websocket channel does not send any pings either so it dies after a while, at least in some cases

**Comment by fi3ework** [comment]
closed in #202
