### ISSUE TITLE
Support generation of TS type definitions

### ISSUE THREAD

**Issue by xaviergonz** [fi3ework/vite-plugin-checker#220]
### Is your feature request related to a problem? Please describe.

I'm planning to use this plugin for a library, this is, to check TS sources as well as generate TS type definitions.

### Describe the solution you'd like

If tsconfig has `declaration: true` then it should generate the type definitions wherever tsconfig `declarationDir` points to (or wherever the default declaration dir is when there is none defined)

### Describe alternatives you've considered

rollup-plugin-typescript2 is capable of this
also I could run tsc to generate the types, but that'd be double the compilation time

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Out of the scope of the plugin in the foreseeable future.
