### ISSUE TITLE
vueTsc option not comaptible with typescript 5

### ISSUE THREAD

**Issue by ole-thoeb** [fi3ework/vite-plugin-checker#229]
### Describe the bug

When using typescript 5 the `vueTsc` option produces unexpected results. In dev mode, all typescript files are transpiled.  It also seems like the check does not finish (I'm currently unable to create a reproduction sample that does).

### Reproduction

1. Click the "Vue3 + vue-tsc" stackblitz link in the readme
2. change the typescript version to `5.0.2`. 
3. run `npm i`
4. add `noEmit: true` to `tsconfig.json`. Stackblitz does not support emit. This kinda fixes the first issue, but should not be needed. 
5. run `npm run dev`

Result: `vue-tsc` finds the error but never finishes

### Expected behavior

Same behavior as `vue-tsc --noemit` (Not transpiling and finishing)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite-plugin-checker: ^0.5.1 => 0.5.1
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by duKD** [comment]
+1

**Comment by WouterSioen** [comment]
I'm having the same problem here

**Comment by fi3ework** [comment]
Partially related to https://github.com/vuejs/language-tools/issues/2613.

**Comment by mlesin** [comment]
> Partially related to [vuejs/language-tools#2613](https://github.com/vuejs/language-tools/issues/2613).

Referred issue seems to be resolved now
