### ISSUE TITLE
Doesn't work in Storybook

### ISSUE THREAD

**Issue by elektronik2k5** [fi3ework/vite-plugin-checker#237]
### Describe the bug

Hello and thanks for creating and maintaining this plugin!

I've configured it to work in my React + TS app. Can it also work in Storybook (v7)? It doesn't appear in CLI nor browser, which makes me think that the plugin is entirely omitted/replaced in the storybook config.

### Reproduction

Create a Vite + TS + React project, add storybook@7 to it. Plugin doesn't appear in Storybook.

### Expected behavior

It should work in Storybook.

### System Info

```shell
System:
    OS: Linux 6.2 Fedora Linux 38 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 8.33 GB / 31.06 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvs/node/18.12.1/x64/bin/node
    Yarn: 3.2.1 - ~/.nvs/node/18.12.1/x64/bin/yarn
    npm: 8.19.2 - ~/.nvs/node/18.12.1/x64/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jcwillox** [comment]
You can add it inside your storybook config and it will work, don't know why it doesn't work inside the normal vite config as storybook is supposed to inherit it.

```ts
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [...],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  // add checker plugin to storybook vite config
  viteFinal: (config) => {
    config.plugins?.push(checker({ typescript: true }));
    return config;
  },
};
```

**Comment by elektronik2k5** [comment]
Yes, that works - thank you!

**Comment by pksunkara** [comment]
@jcwillox Was there a relevant storybook issue? I could take a look on why it doesn't work.

**Comment by jcwillox** [comment]
Not that I'm aware of, I just noticed that storybook wasn't inheriting the plugin unless I added it to the vite config by putting it in the storybook config

**Comment by m-shaka** [comment]
I found that if you comment out these lines of code you can add the plugin in the vite config instead of the storybook config.
https://github.com/fi3ework/vite-plugin-checker/blob/b2c32367cf2e410154194d7730d8830aace898d9/packages/vite-plugin-checker/src/main.ts#L81-L86

Do you have any ideas on why? @fi3ework
