### ISSUE TITLE
Default for `eslint`

### ISSUE THREAD

**Issue by pksunkara** [fi3ework/vite-plugin-checker#269]
### Is your feature request related to a problem? Please describe.

Like how you have a default for `typescript`, I think a default value for `eslint` makes sense too.

### Describe the solution you'd like

```ts
{
  eslint: true
}
```

should be equivalent to:

```ts
{
  eslint: {
    lintCommand: 'eslint .'
  }
}
```

### Additional context

I can send a PR if interested.

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by fi3ework** [comment]
Hmm, that's an interesting proposal. Personally, I prefer using explicit configurations over implicit ones. For example, when examining the boilerplate templates generated by `vite create`, I suggest changing the command to `eslint ./src` if someone wants to lint only the configuration files. For linting other configuration files as well, the command `eslint .` should be used. Moreover, when creating a TypeScript project, it's advisable to modify the command to `eslint . --ext .js,.ts`, especially when working with a Vue project we need to include `.vue`. Taking all these conditions into consideration, I believe it's best to let the user decide, even though it might require a little extra time (probably less than 30 seconds 🤣). However, this approach will help prevent potential future issues that are uncertain.
