### ISSUE TITLE
Vite 5 support

### ISSUE THREAD

**Issue by Kamahl19** [fi3ework/vite-plugin-checker#285]
### Is your feature request related to a problem? Please describe.

[Vite 5](https://vitejs.dev/blog/announcing-vite5.html) has been released.

### Describe the solution you'd like

The peer dependency range in this plugin needs to be updated

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Read the [Contributing Guidelines](https://github.com/fi3ework/vite-plugin-checker/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sjdemartini** [comment]
@Kamahl19 Just out of curiosity, why is it you closed this issue? From what I can tell, there isn't support for Vite 5 yet and I haven't found any related discussion about it. Can it be reopened?
