### ISSUE TITLE
Vite documentation 

### ISSUE THREAD

**Issue by a1dutch** [fi3ework/vite-plugin-checker#289]
### Describe the bug

Hi,

I wanted to use the `initialIsOpen='error'` as per the docs but was getting a typescript error saying only boolean's are allowed.

I figured out this was added after the last release and that the documentation was displaying information for the `main` branch and not `0.6.2`.  It doesn't say anywhere in the documentation it's pointing at `main` and includes unreleased features.

I'd love a release to use this new feature, and also a mention in the docs that its pointing at the main branch.

### Reproduction

go to https://vite-plugin-checker.netlify.app/configuration/config.html and look at `initialIsOpen`, this shows the latest feature from main which is not release yet.

### Expected behavior

documentation should be correct for the latest released version

### System Info

```shell
n/a
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jhoermann** [comment]
@a1dutch So its released now right? Then you could close the issue.

**Comment by fi3ework** [comment]
Yeah, it should be correct now. I'll try to release new a version as the same time as updating the doc.
