### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by strawberry-choco** [fi3ework/vite-plugin-checker#298]
Asking the question no one wants to read here. 😅

**Comment by dschewchenko** [comment]
I think - No. Because maintainer have closed every issue without any comment, just closed "not planned". So we need fork

**Comment by daniluk4000** [comment]
Maintainer seems to be back to OSS tho

![image](https://github.com/fi3ework/vite-plugin-checker/assets/10450717/86fca38c-0d97-4a37-b243-bbec6bc4454a)

**Comment by Kegulf** [comment]
@fi3ework vulnerabilities in dependency, I believe PR #299 solves it.

**Comment by fi3ework** [comment]
I am currently recovering from a long period of burnout and am now addressing the piled-up issues and pull requests. The community has closed some critical issues through their pull requests. I am currently working on version 0.7, which will separate the logic of each checker into its own package. This will prevent the package from becoming a monster with unrelated checkers mixed together. Once version 0.7 is released, I will attempt to merge other pull requests.
