### ISSUE TITLE
why (Vue3 + vue-tsc) so shit compaired to (React + TypeScript	) ? 

### ISSUE THREAD

**Issue by moHaHa** [fi3ework/vite-plugin-checker#310]
### Describe the bug

(Vue3 + vue-tsc) vs  (React + TypeScript)

### Reproduction

(Vue3 + vue-tsc) vs  (React + TypeScript)

### Expected behavior

(Vue3 + vue-tsc) vs  (React + TypeScript)

### System Info

```shell
(Vue3 + vue-tsc) vs  (React + TypeScript)
```

### Additional context

(Vue3 + vue-tsc) vs  (React + TypeScript)

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
TypeScript supports React internally, which vue does not. vue-tsc did a lot of great work to make type check works for vue combined with TypeScript. Please keep nice in the community.

**Comment by 9mm** [comment]
@moHaHa what exactly is better? Im just curious
