### ISSUE TITLE
vscode-uri@3.0.8 'vscode-uri' does not provide an export named 'default'

### ISSUE THREAD

**Issue by yejiajiehz** [fi3ework/vite-plugin-checker#322]
### Describe the bug

```
import pkg from "vscode-uri";
       ^^^
SyntaxError: The requested module 'vscode-uri' does not provide an export named 'default'
```
![image](https://github.com/fi3ework/vite-plugin-checker/assets/1755967/ddbc3d75-4f8a-467c-897a-39f938bb59e5)

### Reproduction

update dependencies vscode-uri@3.0.8

### Expected behavior

```
import { URI } from 'vscode-uri'
```

https://github.com/microsoft/vscode-uri/commit/53e4ca6263f2e4ddc35f5360c62bc1b1d30f27dd

### System Info

```shell
  System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 417.76 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.n/bin/node
    npm: 8.19.4 - ~/.n/bin/npm
    pnpm: 8.5.0 - ~/.n/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.60
    Safari: 16.0
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by so1ve** [comment]
Fixed with latest version
