### ISSUE TITLE
Sync volar runTsc changes

### ISSUE THREAD

**Issue by so1ve** [fi3ework/vite-plugin-checker#351]
### Describe the bug

https://github.com/volarjs/volar.js/pull/222

### Reproduction

N/A

### Expected behavior

N/A

### System Info

```shell
N/A
```

### Additional context

Perhaps extracting the text replacing process into a function would be better.

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fi3ework** [comment]
I'll sync the code.
