### ISSUE TITLE
Typescript message shows as red for "0 errors found" in node ^20.15.1

### ISSUE THREAD

**Issue by gkiely** [fi3ework/vite-plugin-checker#390]
### Describe the bug

<img width="447" alt="image" src="https://github.com/user-attachments/assets/8e68a308-bd1e-49f1-ace1-413bfb8398dd">

### Reproduction

https://github.com/gkiely/vite-plugin-repro

### Expected behavior

Should show as white, so as not to confuse with errors

### System Info

```shell
System:
    OS: macOS 12.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1023.53 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.volta/tools/image/node/20.15.1/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 10.8.0 - ~/.volta/tools/image/npm/10.8.0/bin/npm
    bun: 1.1.25 - ~/.bun/bin/bun
    Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 114.1.52.129
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Safari: 17.5
  npmPackages:
    vite-plugin-checker: ^0.7.2 => 0.7.2
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by hooch** [comment]
Probably this should be a different issue, but perhaps it's in a similar part of the code.

Everything gets underlined in red, regardless of whether it's a warning or an error.

<img src="https://github.com/user-attachments/assets/234ed3ad-7d1a-49d9-8915-27bc507d0d79"  width=460>

**Comment by gkiely** [comment]
Fix is to change this line: https://github.com/fi3ework/vite-plugin-checker/pull/393/files#diff-41d1c7c4522702a7fffc786aff11b20c2391952df70678d1ffe12b6f934b9a0dR111
`const color = 'white';`

![image](https://github.com/user-attachments/assets/1b0afb33-c4de-45c1-b87d-411b09636798)
![image](https://github.com/user-attachments/assets/e2dbb9b3-a015-4f33-b2db-f1c073b42785)

**Comment by hooch** [comment]
This seems to be fixed recently.

<img width="485" alt="Screenshot 2024-11-22 at 09 33 03" src="https://github.com/user-attachments/assets/be6a0baa-c69a-4ae7-b476-99893ab54e3d">
