### ISSUE TITLE
[Biome] Found 0 error and 0 warning

### ISSUE THREAD

**Issue by seedydocloop** [fi3ework/vite-plugin-checker#409]
### Describe the bug

Biome finds no error and warnings in my code when launched via vite-plugin-checker, whereas it finds some when launched via npm

### Reproduction

`vite.config.ts`
```
            checker({
                biome: true,
                typescript: true,
                enableBuild: true,
                overlay: true,
                terminal: true,
            })
```

`biome.json` is located in the same folder as vite config.

Running the following npm command outputs errors:
```
biome lint --write ./src
```

Whereas running `npm start`, outputs :
```
[Biome] Found 0 error and 0 warning
```

### Expected behavior

Since biome finds errors when run via npm script, I'd expect the same error output from vite-plugin-checker's integration of biome.

```
The number of diagnostics exceeds the number allowed by Biome.
Diagnostics not shown: 92.
Checked 155 files in 38ms. No fixes applied.
Found 1 error.
Found 111 warnings.
lint 
Some errors were emitted while running checks.
```

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.20 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.8.0 - /opt/homebrew/bin/pnpm
    Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 17.6
  npmPackages:
    vite-plugin-checker: ^0.8.0 => 0.8.0 
```

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by seedydocloop** [comment]
Closing, I do not reproduce. Most likely an issue with biome config

**Comment by ucimo** [comment]
I have this same issue... When I use 'vite-plugin-biome' it works fine, but not via 'vite-plugin-checker'.
