### ISSUE TITLE
README is incorrect on ESLint configuration

### ISSUE THREAD

**Issue by fgblomqvist** [fi3ework/vite-plugin-checker#46]
It does
```
extensions: '.ts',
```
for the first ESLint config, however, it needs to be an array. Should probably be changed to:
```
extensions: ['.ts'],
```

**Comment by fi3ework** [comment]
Thanks. Docs fixed in https://github.com/fi3ework/vite-plugin-checker/commit/1403f6fe9bc66486e3dff5597f8927c28ff2dfe9
