### ISSUE TITLE
Release 0.3.3

### ISSUE THREAD

**Issue by fgblomqvist** [fi3ework/vite-plugin-checker#53]
Would it be possible to release a new version with the ESLint fixes? 🙂

**Comment by fi3ework** [comment]
I am AFK for now. I will release once I come back to computer ASAP (about 4 hours later 😅).

**Comment by fi3ework** [comment]
Maybe we should introduce semantic release 🤔

**Comment by fgblomqvist** [comment]
Thanks, and yeah, might be cool 🙃

**Comment by fi3ework** [comment]
@fgblomqvist 0.3.3 released. Thank you for your contribution! 🤩
