### ISSUE TITLE
Stylelint support

### ISSUE THREAD

**Issue by fgblomqvist** [fi3ework/vite-plugin-checker#57]
Fantastic work on this so far! 🎉 

Another handy tool to support could be stylelint. I think they're pretty much the universal CSS/SCSS linter. [They have a Node API](https://stylelint.io/user-guide/usage/node-api).

**Comment by fi3ework** [comment]
Good idea! I think the implementation will be pretty much like ESLint. 🤔

**Comment by ModyQyW** [comment]
Anyone working on it? I want to make a pr for this.

**Comment by amstiel** [comment]
I see that PR was merged. How can I try stylelint support in my project? I don't see new version in npm.

**Comment by ModyQyW** [comment]
It seems that the stylelint part requires more testing? The tests are mainly done by @fi3ework . Let's wait patiently. ❤️

If you want to try stylelint support, maybe you can clone, build and link to your project.

**Comment by ModyQyW** [comment]
Should be included in v0.5.2.
