### ISSUE TITLE
enableBuild causes no files to be outputted

### ISSUE THREAD

**Issue by fgblomqvist** [fi3ework/vite-plugin-checker#60]
If we have `enableBuild` set to true (the default), no files get outputted when building the app. Dev mode still works fine, but doing `vite build` results in this being the last message in terminal:
```
✓ 5396 modules transformed.
```
As in, it seems to skip rendering the chunks? Setting `enableBuild` to false makes the build work again.

**Comment by fi3ework** [comment]
could you provide a minimal re-produce repo or show the Vite configuration? Maybe some checker failed silently? 🤔

**Comment by fgblomqvist** [comment]
This is our vite config (with enableBuild set to false, when we set it to true or remove it the build stops working):
```
import reactRefresh from '@vitejs/plugin-react-refresh';
import checker from 'vite-plugin-checker';
import svgr from 'vite-plugin-svgr';
import tsconfigPaths from 'vite-tsconfig-paths';

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    target: 'es2018',
  },
  plugins: [
    reactRefresh(),
    tsconfigPaths(),
    svgr(),
    checker({
      enableBuild: false,
      eslint: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        files: ['./src'],
      },
      typescript: true,
    }),
  ],
});
```

**Comment by fgblomqvist** [comment]
Did some further testing and if I do e.g.
```
    checker({
      enableBuild: true,
    }),
```
(as in, nothing enabled)
The build just stops really fast. So yeah it seems like whenever vite-plugin-checker fails the whole build fails? But it all happens silently. If I turn off `enableBuild` things work.

**Comment by fgblomqvist** [comment]
Actually I'm guessing that what's happening is that as soon as `checker` finishes, the build ends for some reason.

**Comment by fgblomqvist** [comment]
Found the issue, it's here:
https://github.com/fi3ework/vite-plugin-checker/blob/main/packages/vite-plugin-checker/src/main.ts#L76-L81

That code could be more readable if you made the `buildStart` async and then just awaited:
```ts
const exitCodes = await Promise.all(checkers.map((checker) => spawnChecker(checker, userConfig, localEnv)))
const exitCode = exitCodes.find((code) => code !== 0) || 0;
process.exit(exitCode)
```

Now it's pretty clear that `vite-plugin-checker` kills the process as soon as it's done, no matter what. The last line above should be changed to:
```ts
if (exitCode !== 0) process.exit(exitCode);
```
