### ISSUE TITLE
userConfig: { overlay: false } not working.

### ISSUE THREAD

**Issue by IndexXuan** [fi3ework/vite-plugin-checker#7]
https://github.com/fi3ework/vite-plugin-checker/blob/1334c1817b9e8a61ef8dd90bddbc052294ba7dd3/packages/checker-vls/src/main.ts#L14

It seems that overlay is assigned by never use. Am I wrong ?

**Comment by IndexXuan** [comment]
https://github.com/fi3ework/vite-plugin-checker/pull/8

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/122520275-fa901700-d045-11eb-8172-4dca910dcaee.png)
also, should the error message end with `\n` so that the codeframe works well. line 2 was at the end of the last line right now.

**Comment by fi3ework** [comment]
released vite-plugin-checker-vls@0.1.1  https://www.npmjs.com/package/vite-plugin-checker-vls
