### ISSUE TITLE
Clear terminal between outputs

### ISSUE THREAD

**Issue by dkoujelev** [fi3ework/vite-plugin-checker#75]
Would be nice if the terminal was cleared before outputting new warnings/errors instead of appending them.

![image](https://user-images.githubusercontent.com/22074219/135319506-de58e483-8a0f-4cb1-b1a4-9996480ed1c7.png)

**Comment by szamanr** [comment]
it should be configurable with appending as default, and clearing as an option.

**Comment by fi3ework** [comment]
For now. vite-plugin-checker leverages the default terminal clean behavior of Vite.
- If scroll to the bottom of the terminal, the tty output will be cleaned by Vite update info which is desired.
- If not scrolled to the bottom of the terminal, then you will see the full history log output by vite-plugin-checker.
vite-plugin-checker should clean the log before code updating by itself. It will be implemented in the future. Now you could scroll the bottom and let Vite clean the log for you in terminal.

**Comment by riderx** [comment]
Hey i got the clear issue on nuxt i loose the history of what has been wrote by nuxt, and often get a message of one error without any info, if i disable the type check it stops.

https://github.com/fi3ework/vite-plugin-checker/assets/4084527/73d6ac83-376a-4cd2-87fa-4e85b524b9e4

https://github.com/fi3ework/vite-plugin-checker/assets/4084527/e79ff68b-82ae-4459-8b70-0b357f1376b6

Error:
<img width="960" alt="CleanShot 2023-06-15 at 01 48 24@2x" src="https://github.com/fi3ework/vite-plugin-checker/assets/4084527/6085bfd4-d96a-4942-82e6-b3a77759df52">

Can we have a way to disable this ?
