### ISSUE TITLE
config.eslint configFile, maxWarnings giving errors

### ISSUE THREAD

**Issue by iKnowMagic** [fi3ework/vite-plugin-checker#77]
Hi,

When trying to configure the eslint parameters _configFile_ or _maxWarnings_ I get errors. Thoughts?
The parameters _files_ and _extensions_ seem to be working fine.

I am using:

"eslint": "^7.32.0",
"vite-plugin-checker": "^0.3.4"

See the screenshots below.

![image](https://user-images.githubusercontent.com/8712362/138329339-cb4176df-8301-4250-8f15-7826e2ff3fc3.png)

![image](https://user-images.githubusercontent.com/8712362/138329380-39b86fa8-edce-4e09-94b3-70b8c97f8d64.png)

Many thanks for looking into this.

**Comment by fi3ework** [comment]
Sorry, `max-warning` is documented in README but it's not released in 0.3.4 😅.
I'm working on 0.4.0 which will pass options to ESLint in a more transparent way. But still, `max-warnings` will only work in build mode cause only the ESLint CLI respect it, see https://github.com/eslint/eslint/blob/6f940c3ce715327f282c197d0f71b91848e5d83d/lib/cli.js#L322. I think log level is needed to be a compensation to max-warnings. 0.4.0 will be released these days.

**Comment by fi3ework** [comment]
tracks in https://github.com/fi3ework/vite-plugin-checker/issues/79
