### ISSUE TITLE
Warnings are being displayed as errors

### ISSUE THREAD

**Issue by iKnowMagic** [fi3ework/vite-plugin-checker#78]
Hi,

I have a rule as a warning and yet, it triggers a blocking popup box, that seems to be an error rather than a warning. Is there a way to avoid displaying warnings?

Thanks.

![image](https://user-images.githubusercontent.com/8712362/138352600-13c821c9-e847-41db-9f75-c1a6786f0c1a.png)

**Comment by GabriFila** [comment]
Yes it would be great to have this feature!
