### ISSUE TITLE
vls configuration currently does not recognize setup+ts

### ISSUE THREAD

**Issue by jerrywu001** [fi3ework/vite-plugin-checker#82]
First of all, this is a very powerful plug-in, thanks to the author!

But I have a problem, it would be perfect if anyone can improve it.

----------------------------------------------------------------
Scenes：(a simple demo with setup + ts)

My needs：

> watch in the devlopment environment，So I can't use vueTsc directly(Because it only applies to the build environment)

```js
<template>
  <p v-cloak>{{ name }}</p>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
const name = ref('test');
</script>

```

The following error will appear：

- ERROR(VLS)  Module '"xxx.vue"' has no default export

- ERROR(VLS)  Property 'name' does not exist on type 'unknown'.

- ERROR(VLS)  'name' is declared but its value is never read.

vls configuration currently does not recognize setup+ts

but `typescript: true` can only applies to xxx.tsx in the development environment，it does not meet my needs

----------------------
Need your help， Thanks!

**Comment by zerogu** [comment]
I ran into the same problem

**Comment by fi3ework** [comment]
Sorry for the late response. This is vls(vetur) related feature request. According to https://github.com/vuejs/vetur/issues/2296, I think it's not supported by vls now. And TypeScrpit do not support `.vue` file unless using a customized lang server like vls or vue-tsc.
I think we have to wait for vue-tsc support watch mode. Maybe we can run `vue-tsc --noEmit` fully whenever any file changed as a simple workaround for now.

**Comment by MoishyS** [comment]
>Maybe we can run vue-tsc --noEmit fully whenever any file changed as a simple workaround for now.

@fi3ework I am using `vite build --watch` and it looks like it does add run `vue-tsc --noEmit` fully, my issue is that it stops the watch if it has any ts errors.

**Comment by fi3ework** [comment]
vue-tsc in watch mode is supported since 0.4.4. Vue3 can drop VLS now. Have a try!
