### ISSUE TITLE
No way to customize VLS settings

### ISSUE THREAD

**Issue by ascott18** [fi3ework/vite-plugin-checker#85]
Unless I'm missing something, it doesn't appear there's a way to customize the settings passed to VLS.

I want to perform type checking on my `<script lang=ts>`, but not on my templates. It seems these settings are hardcoded in `initParams` and there's no way to override them. Is there something I'm missing?

**Comment by ascott18** [comment]
I'm working on a PR for this.

**Comment by fi3ework** [comment]
Sorry for the late response, but I believe you can customize the VLS' configuration by https://vuejs.github.io/vetur/reference/#example. Would you like to have a try?

**Comment by ascott18** [comment]
That's true, but that affects VS Code's behavior as well.

I want to be able to turn off template and interpolation validation for the build, but keep those enabled within VS Code. Reason being is that I want that feedback in VS code because its often useful, but sometimes there are typescript errors within the template (usually `Object is possibly 'null'`) that are not actually real errors. Typically one would suppress these with a Typescript definitely-assigned `!`, or a null-propagating `?.` but in Vue 2, typescript syntax cannot be used in templates, nor can newer JS operators like `?.`.

Essentially, I'm trying to replicate the behavior of vue-cli. Typescript validation on `<script lang="ts">` blocks, but not on the template.

I submitted a PR #86 that enables the vetur settings to be overridden just for this plugin.
