### ISSUE TITLE
vls checker console format error

### ISSUE THREAD

**Issue by fi3ework** [fi3ework/vite-plugin-checker#9]
![image](https://user-images.githubusercontent.com/6322673/122520275-fa901700-d045-11eb-8172-4dca910dcaee.png)
also, should the error message end with `\n` so that the codeframe works well. line 2 was at the end of the last line right now.

_Originally posted by @IndexXuan in https://github.com/fi3ework/vite-plugin-checker/issues/7#issuecomment-863807623_

**Comment by fi3ework** [comment]
hmmm, still an open issue of log-update https://github.com/sindresorhus/log-update/issues/49

**Comment by IndexXuan** [comment]
thanks very much.
also can we not log this information ?
![image](https://user-images.githubusercontent.com/6322673/123365513-f8c7d580-d5a8-11eb-8c89-9f4b49da42a2.png)

**Comment by fi3ework** [comment]
Yes, I think this should be eliminated and only display when enabling a `verbose` or `debug` config. I'll take a look into VLS.

**Comment by fi3ework** [comment]
fixed in 0.2.0

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/124552490-34df1e00-de66-11eb-9e4d-9586220cc772.png)

The log looks pretty now with new colors. 

It seems that the `2 |   <div class="home">` is still in the wrong place(not in the next line). doesn't it ?

**Comment by fi3ework** [comment]
@IndexXuan Good catch, just released vite-plugin-checker-vl@0.2.1 and it's fixed. Thanks.

![image](https://user-images.githubusercontent.com/12322740/124554229-517c5580-de68-11eb-8176-caa85cbbf9b5.png)

**Comment by IndexXuan** [comment]
@fi3ework 
You are lighting fast than vite HMR.
