### ISSUE TITLE
TS isolatedModules setting conflciting with vite-plugin-checker

### ISSUE THREAD

**Issue by templeman15** [fi3ework/vite-plugin-checker#90]
Hello,

Thanks for this library, it's great!

I did want to ask about `isolatedModules` being set to `true` in `tsconfig.json`. 

The Vite docs, write that it should be set to true right [here](https://vitejs.dev/guide/features.html#typescript-compiler-options). 

The only way I could get this plugin to show any of the typescript errors is if it was set to false or removed it from tsconfig. 

Thanks again!

**Comment by fi3ework** [comment]
I didnot understand clearly due to the description. You mean you cannot get any error if isolatedModules is set to true?

**Comment by templeman15** [comment]
> I didnot understand clearly due to the description. You mean you cannot get any error if isolatedModules is set to true?

@fi3ework yes that is correct. If I set isolatedModules to true as the Vite docs recommend your package stops working (no typescript errors show in browser and no output in the Vite server console).

**Comment by fi3ework** [comment]
Cannot produce the issue. I made a stackblitz playground and set `isolatedModuels` to true and everything goes well. Could you try to reproduce and provide a link of stackblitz? https://stackblitz.com/edit/vitejs-vite-tkbtxj?file=tsconfig.json
